name: st_stefano_quiz_game
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.19.2'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: LalezarRegular
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: Athanasius
      fonts:
        - asset: assets/fonts/Athanasius.ttf


  uses-material-design: true

  assets:
    - assets/images/
